version: '3.7'
name: nestjs-architecture

services:
  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data

  app:
    image: baledev/nestjs-architecture:latest
    container_name: nestjs-architecture
    build:
      context: .
      dockerfile: Dockerfile.production
    ports:
      - '${PORT}:${PORT}'
    environment:
      - NODE_ENV=development
      - DB_HOST=mongodb
      - REDIS_HOST=redis
    env_file:
      - /env/.env.development
    depends_on:
      - redis
      - mongodb

  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - 27018:27017
    volumes:
      - mongodb:/data

volumes:
  redis:
    driver: local

  mongodb:
    driver: local
