version: '3.8'

services:
  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data

  nestjs_api:
    build:
      context: .
      dockerfile: Dockerfile.production
    ports:
      - '${PORT}:${PORT}'
    environment:
      - NODE_ENV=production
      - DB_HOST=mongodb
      - REDIS_HOST=redis
    env_file:
      - ./.env.production
    depends_on:
      - redis
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - 27018:27017
    volumes:
      - mongodb:/data

volumes:
  redis:
    driver: local

  mongodb:
    driver: local
